# Generated by Django 6.0.6 on 2026-06-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattress',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
