# Generated by Django 6.0.6 on 2026-06-23 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattress', '0002_mattress_width_alter_mattress_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mattress',
            options={'ordering': ['name'], 'verbose_name': 'mattress', 'verbose_name_plural': 'mattresses'},
        ),
        migrations.AlterField(
            model_name='mattress',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mattresses/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='warranty_months',
            field=models.PositiveIntegerField(verbose_name='warranty months'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('address', models.TextField(verbose_name='address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MattressInstance',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='serial number')),
                ('is_warranty_active', models.BooleanField(default=False, verbose_name='warranty active')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='activation date')),
                ('manufacture_date', models.DateField(verbose_name='manufacture date')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mattress_instances', to='mattress.customer', verbose_name='customer')),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='mattress.mattress', verbose_name='mattress')),
            ],
            options={
                'verbose_name': 'mattress instance',
                'verbose_name_plural': 'mattress instances',
                'ordering': ['-manufacture_date', 'serial_number'],
            },
        ),
    ]
