# Generated by Django 6.0.6 on 2026-06-28 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattress', '0003_alter_mattress_options_alter_mattress_description_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattressinstance',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mattress_instances', to='users.customer', verbose_name='customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
