# Generated by Django 6.0.6 on 2026-07-03 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattress', '0004_alter_mattressinstance_customer_delete_customer'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattress',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='average rating'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='height',
            field=models.IntegerField(default=0, verbose_name='height (cm)'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is available'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='long_description',
            field=models.TextField(blank=True, default='', verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='review count'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='subtitle'),
        ),
        migrations.CreateModel(
            name='MattressFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='mattress.mattress')),
            ],
            options={
                'verbose_name': 'mattress FAQ',
                'verbose_name_plural': 'mattress FAQs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MattressFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='feature title')),
                ('icon_name', models.CharField(blank=True, default='', max_length=50, verbose_name='lucide icon name')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='mattress.mattress')),
            ],
            options={
                'verbose_name': 'mattress feature',
                'verbose_name_plural': 'mattress features',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MattressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mattresses/gallery/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mattress.mattress')),
            ],
            options={
                'verbose_name': 'mattress image',
                'verbose_name_plural': 'mattress images',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MattressProCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('type', models.CharField(choices=[('PRO', 'Pro'), ('CON', 'Con')], max_length=3, verbose_name='type')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros_cons', to='mattress.mattress')),
            ],
            options={
                'verbose_name': 'mattress pro/con',
                'verbose_name_plural': 'mattress pros & cons',
                'ordering': ['type', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='MattressSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='size label')),
                ('width', models.IntegerField(verbose_name='width (cm)')),
                ('length', models.IntegerField(verbose_name='length (cm)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('in_stock', models.BooleanField(default=True, verbose_name='in stock')),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='mattress.mattress')),
            ],
            options={
                'verbose_name': 'mattress size',
                'verbose_name_plural': 'mattress sizes',
                'ordering': ['width', 'length'],
            },
        ),
        migrations.CreateModel(
            name='MattressSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='specification key')),
                ('value', models.CharField(max_length=255, verbose_name='specification value')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='mattress.mattress')),
            ],
            options={
                'verbose_name': 'mattress specification',
                'verbose_name_plural': 'mattress specifications',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(verbose_name='rating')),
                ('title', models.CharField(max_length=200, verbose_name='review title')),
                ('body', models.TextField(verbose_name='review body')),
                ('pros', models.TextField(blank=True, default='', verbose_name='pros')),
                ('cons', models.TextField(blank=True, default='', verbose_name='cons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='is approved')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.customer')),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mattress.mattress')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
