# Generated by Django 6.0.6 on 2026-07-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattress', '0005_mattress_average_rating_mattress_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattressinstance',
            name='buyer_address',
            field=models.TextField(blank=True, default='', verbose_name='buyer address'),
        ),
        migrations.AddField(
            model_name='mattressinstance',
            name='buyer_first_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='buyer first name'),
        ),
        migrations.AddField(
            model_name='mattressinstance',
            name='buyer_last_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='buyer last name'),
        ),
        migrations.AddField(
            model_name='mattressinstance',
            name='buyer_phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='buyer phone number'),
        ),
        migrations.AddField(
            model_name='mattressinstance',
            name='buyer_postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='buyer postal code'),
        ),
    ]
