# Generated by Django 6.0.6 on 2026-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattress', '0006_mattressinstance_buyer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattress',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='mattresssize',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price'),
        ),
    ]
