# Generated by Django 6.0.6 on 2026-07-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattress', '0007_alter_mattress_price_alter_mattresssize_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattress',
            name='is_on_off',
            field=models.BooleanField(default=False, verbose_name='on sale'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='off_percentage',
            field=models.PositiveIntegerField(default=0, help_text='0-100', verbose_name='discount percentage'),
        ),
    ]
