# Generated by Django 6.0.6 on 2026-07-29 19:09

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models
from django.db.models import Avg, Count

DEFAULT_RATING = Decimal("5.00")


def recompute_ratings(apps, schema_editor):
    """Bring every existing row in line with the new rule.

    Changing the field default only affects rows inserted from now on. Rows
    already in the table were written under the old default of 0, so an
    unreviewed mattress still reads as zero stars until it is rewritten here.
    Recompute from the approved reviews rather than just patching the zeros, so
    any cache that drifted out of step (e.g. a review approved via a bulk
    .update() before the signals existed) is corrected in the same pass.
    """
    Mattress = apps.get_model("mattress", "Mattress")
    for mattress in Mattress.objects.all().iterator():
        stats = mattress.reviews.filter(is_approved=True).aggregate(
            avg=Avg("rating"), cnt=Count("id")
        )
        count = stats["cnt"] or 0
        average = stats["avg"]
        if count == 0 or average is None:
            rating = DEFAULT_RATING
        else:
            rating = Decimal(average).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        Mattress.objects.filter(pk=mattress.pk).update(
            average_rating=rating, review_count=count
        )


def reset_unreviewed_to_zero(apps, schema_editor):
    """Reverse of the above: restore the old zero-for-unreviewed convention."""
    Mattress = apps.get_model("mattress", "Mattress")
    Mattress.objects.filter(review_count=0).update(average_rating=Decimal("0"))


class Migration(migrations.Migration):

    dependencies = [
        ('mattress', '0009_mattressinstance_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattress',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), editable=False, max_digits=3, verbose_name='average rating'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='review_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='review count'),
        ),
        migrations.RunPython(recompute_ratings, reset_unreviewed_to_zero),
    ]
