# Generated by Django 6.0.6 on 2026-08-23 20:46

from datetime import datetime, time

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def set_status_from_boolean(apps, schema_editor):
    """True -> APPROVED, False -> UNREGISTERED (the field default).

    Also backfills warranty_submitted_at from activation_date at local
    midnight, so no legacy approved row sorts as null in the review queue.
    """
    MattressInstance = apps.get_model("mattress", "MattressInstance")
    tz = timezone.get_current_timezone()
    for row in MattressInstance.objects.filter(is_warranty_active=True).iterator():
        submitted_at = None
        if row.activation_date is not None:
            submitted_at = timezone.make_aware(
                datetime.combine(row.activation_date, time.min), tz
            )
        MattressInstance.objects.filter(pk=row.pk).update(
            warranty_status="APPROVED", warranty_submitted_at=submitted_at
        )


def set_boolean_from_status(apps, schema_editor):
    """Reverse. Lossy: PENDING and REJECTED both collapse to False, so
    reversing discards the fact that a request was submitted or declined."""
    MattressInstance = apps.get_model("mattress", "MattressInstance")
    MattressInstance.objects.filter(warranty_status="APPROVED").update(
        is_warranty_active=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('mattress', '0011_mattress_category_and_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Order matters: is_warranty_active must still exist when RunPython runs
    # forward, and must have been restored before it runs backward. AddFields
    # -> RunPython -> RemoveField gives both.
    operations = [
        migrations.AddField(
            model_name='mattressinstance',
            name='warranty_rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='warranty rejection reason'),
        ),
        migrations.AddField(
            model_name='mattressinstance',
            name='warranty_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='warranty reviewed at'),
        ),
        migrations.AddField(
            model_name='mattressinstance',
            name='warranty_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_warranties', to=settings.AUTH_USER_MODEL, verbose_name='warranty reviewed by'),
        ),
        migrations.AddField(
            model_name='mattressinstance',
            name='warranty_status',
            field=models.CharField(choices=[('UNREGISTERED', 'Unregistered'), ('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='UNREGISTERED', max_length=12, verbose_name='warranty status'),
        ),
        migrations.AddField(
            model_name='mattressinstance',
            name='warranty_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='warranty submitted at'),
        ),
        migrations.RunPython(set_status_from_boolean, set_boolean_from_status),
        migrations.RemoveField(
            model_name='mattressinstance',
            name='is_warranty_active',
        ),
    ]
