"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-ffshc4%#=-41fw^5z&u%u$o%98=02ju-c%1tuas1fqrhz-=2d7',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Domains allowed to submit the admin/session CSRF form (comma-separated,
# full scheme + host, e.g. https://salyco.ir). Required when DEBUG=False
# and serving the admin over a real domain.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8080,http://127.0.0.1:8080,http://localhost:5173,http://127.0.0.1:5173').split(',') if o.strip()
]

# ── HTTPS / reverse-proxy security ───────────────────────────────────────────
# In production Django runs behind Caddy (TLS) → nginx → gunicorn, all speaking
# plain HTTP internally. Trust the X-Forwarded-Proto header so request.is_secure()
# is correct, absolute URLs (warranty QR codes) come out as https, and admin
# CSRF over HTTPS is accepted. nginx is configured to forward Caddy's real proto.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Only harden cookies/redirects/HSTS when not in DEBUG, so local http dev works.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS: tell browsers to always use HTTPS for this host.
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Applies to views that set throttle_scope = "otp": the unauthenticated
        # start/verify endpoints. Every start call spends money at SMS.ir and
        # answers "is this number registered?", so it is rate-limited per IP.
        # Generous enough for a mistyped number and a resend or two.
        "otp": "12/hour",
    },
}

SIMPLE_JWT = {
    # Sliding idle window: every refresh rotates the refresh token and resets its
    # clock, so activity extends the session and inactivity ends it. The frontend
    # (src/context/AuthContext.jsx) refreshes on a keep-alive tick while the user
    # is interacting, and hard-logs-out at IDLE_TIMEOUT_MS of inactivity.
    #
    # INVARIANT: REFRESH_TOKEN_LIFETIME must exceed the frontend IDLE_TIMEOUT_MS
    # (30 min). SIMPLE_JWT LEEWAY is 0 — there is no grace period — so a token
    # expiring at exactly 30 min makes the «ادامه نشست» button fail at 29:59.
    #
    # Worst-case server-side validity after the last user interaction =
    #   REFRESH_TOKEN_LIFETIME + frontend KEEPALIVE_INTERVAL_MS = 32 min.
    # The 30-minute figure is enforced exactly by the client; this is the backstop.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=31),
    "ROTATE_REFRESH_TOKENS": True,
    # Deliberately off. Blacklisting would invalidate a token another tab already
    # has in flight (N tabs each run the keep-alive), causing spurious logouts.
    # It also requires the token_blacklist app, whose OutstandingToken row is
    # written on every login *and every rotation* — with rotation alone,
    # refresh.outstand() is a no-op and the whole scheme costs zero DB writes.
    "BLACKLIST_AFTER_ROTATION": False,
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "rest_framework",
    "core",
    "mattress",
    "articles",
    "users",
    "contact",
    "search",
    "orders",
    "payments",
    "banners",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", 
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
if os.getenv('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'db'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Serve collected static files directly from gunicorn
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ── SMS.ir Configuration ──────────────────────────────────────────────────────
# SMS.ir API key from https://sms.ir/panel/settings
SMS_IR_API_KEY = os.getenv('SMS_IR_API_KEY', 'JYhqBLNqO9Uk2f6s8ZYjbBJbyUXP14ws5cfSOhlc5zb5tkmA')

# OTP template ID from SMS.ir panel (template must contain #code# placeholder)
SMS_IR_TEMPLATE_ID = int(os.getenv('SMS_IR_TEMPLATE_ID', 389724))

# Transactional (non-OTP) template IDs — see users/notifications.py. Each is
# sent through the same /send/verify pattern endpoint as the OTP above, and the
# parameter names sent for each are the #placeholders# that template must use:
#   welcome  → #PHONE#, #NAME#                     (first-time registration only)
#   warranty → #NAME#, #TIME#, #DATE#, #PHONE#     (warranty activation)
#   order    → #ORDER_NUMBER#, #LINK#              (order placed)
# The order template hard-codes the link origin ("https://salyco.ir/#LINK#")
# because SMS.ir rejects a parameter value containing a URL, so #LINK# receives
# a root-relative path and FRONTEND_BASE_URL does not apply to it.
SMS_IR_TEMPLATE_WELCOME = int(os.getenv('SMS_IR_TEMPLATE_WELCOME', 596133))
SMS_IR_TEMPLATE_WARRANTY = int(os.getenv('SMS_IR_TEMPLATE_WARRANTY', 475048))
SMS_IR_TEMPLATE_ORDER = int(os.getenv('SMS_IR_TEMPLATE_ORDER', 248731))

# ── Zibal payment gateway (IPG) ───────────────────────────────────────────────
# Merchant key from the Zibal panel. "zibal" is the test account documented in
# api-1.json — it exercises the whole flow without moving real money, so it is
# the default and the production key arrives via .env with no code change.
ZIBAL_MERCHANT = os.getenv('ZIBAL_MERCHANT', 'zibal')

# Origin Zibal redirects the customer's browser back to. Must be public HTTPS —
# Zibal drives a real browser to it, so localhost cannot work for an end-to-end
# test, and a non-http(s) value is refused with result 106. Empty falls back to
# the request's own host, which is correct for the single-origin nginx
# deployment where /api is proxied to Django.
ZIBAL_CALLBACK_BASE_URL = os.getenv('ZIBAL_CALLBACK_BASE_URL', '')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOW_ALL_ORIGINS = True  
CORS_ALLOW_CREDENTIALS = True  

# Additional CORS settings for development
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Base URL used to build absolute links (warranty QR codes). Set explicitly in
# production (https://salyco.ir) or for LAN phone testing (http://<lan-ip>:8080).
# When empty, get_warranty_public_url() falls back to the request's own host.
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "")