# Generated by Django 6.0.6 on 2026-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_time_preference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ترجیح زمان تماس'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تماس مشتری'),
        ),
    ]
