# Generated by Django 6.0.6 on 2026-09-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattress', '0012_warranty_status'),
        ('orders', '0004_shorten_order_public_token'),
        ('users', '0002_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed amount')], default='PERCENT', max_length=10, verbose_name='discount type')),
                ('percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='percent')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='amount (Toman)')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='maximum discount')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='minimum order amount')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='starts at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='usage limit')),
                ('per_customer_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='per-customer limit')),
                ('applies_to_all_products', models.BooleanField(default=True, verbose_name='applies to all products')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='coupon code'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='discount amount'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.coupon', verbose_name='coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.coupon', verbose_name='coupon'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='amount (Toman)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='orders.coupon', verbose_name='coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.customer', verbose_name='customer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redemption', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'coupon redemption',
                'verbose_name_plural': 'coupon redemptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.coupon', verbose_name='coupon')),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mattress.mattress', verbose_name='product')),
            ],
            options={
                'verbose_name': 'coupon product',
                'verbose_name_plural': 'coupon products',
                'unique_together': {('coupon', 'mattress')},
            },
        ),
    ]
