# Generated by Django 6.0.6 on 2026-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='برای متن جایگزین تصویر (alt) و فهرست پنل مدیریت استفاده می\u200cشود.', max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
