# Generated by Django 6.0.6 on 2026-09-23 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='نشانی')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام')),
                ('author_type', models.CharField(choices=[('Person', 'شخص'), ('Organization', 'سازمان / تحریریه')], default='Person', help_text='مشخص می\u200cکند در داده\u200cهای ساختاریافته به\u200cعنوان شخص معرفی شود یا سازمان.', max_length=20, verbose_name='نوع')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='سمت')),
                ('short_bio', models.TextField(blank=True, max_length=400, verbose_name='معرفی کوتاه')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='لینکدین')),
                ('instagram_url', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('website_url', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='نشانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('description', models.TextField(blank=True, help_text='زیر عنوان صفحه دسته\u200cبندی نمایش داده می\u200cشود.', max_length=300, verbose_name='توضیح')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان سئو')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات سئو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مقاله',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مقاله',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Salyco', max_length=80, verbose_name='نام برند')),
                ('brand_name_fa', models.CharField(default='سالیکو', max_length=80, verbose_name='نام برند (فارسی)')),
                ('default_title_suffix', models.CharField(default='سالیکو', help_text='به انتهای عنوان صفحه\u200cهایی که عنوان سئوی اختصاصی ندارند اضافه می\u200cشود.', max_length=40, verbose_name='پسوند پیش\u200cفرض عنوان')),
                ('default_meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات پیش\u200cفرض')),
                ('instagram_url', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram_url', models.URLField(blank=True, verbose_name='تلگرام')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='لینکدین')),
                ('aparat_url', models.URLField(blank=True, verbose_name='آپارات')),
                ('default_og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='تصویر پیش\u200cفرض اشتراک\u200cگذاری')),
                ('organization_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='لوگوی سازمان')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'تنظیمات سئو',
                'verbose_name_plural': 'تنظیمات سئو',
            },
        ),
    ]
