# Generated by Django 6.0.6 on 2026-09-23 06:17

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articleauthor_articlecategory_globalseosettings'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='زیرعنوان')),
                ('excerpt', models.TextField(max_length=500, verbose_name='خلاصه')),
                ('hero_image_alt', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر شاخص')),
                ('body', wagtail.fields.StreamField([('heading', 3), ('paragraph', 4), ('quote', 9), ('image', 15), ('callout', 19), ('faq', 24), ('cta', 33)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'متن عنوان'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3')], 'help_text': 'H1 فقط برای عنوان خود مقاله است.', 'label': 'سطح عنوان'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'برای پیوند مستقیم به این بخش. خالی بگذارید تا از متن ساخته شود.', 'label': 'شناسه لنگر', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1), ('anchor_id', 2)]], {}), 4: ('articles.blocks.ParagraphBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'متن نقلقول'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'نام گوینده', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'سمت یا منبع', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'label': 'نشانی منبع', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('quote', 5), ('source_name', 6), ('source_title', 7), ('source_url', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'تصویر'}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'توضیح تصویر برای صفحهخوانها و موتورهای جستوجو.', 'label': 'متن جایگزین', 'required': False}), 12: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'اگر تصویر فقط تزئینی است، متن جایگزین لازم نیست.', 'label': 'تصویر تزئینی است', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'توضیح زیر تصویر', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'عکس از', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('image', 10), ('alt_text', 11), ('decorative', 12), ('caption', 13), ('credit', 14)]], {}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'اطلاعات'), ('tip', 'نکته'), ('warning', 'هشدار'), ('important', 'مهم')], 'label': 'نوع'}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'عنوان', 'required': False}), 18: ('wagtail.blocks.TextBlock', (), {'label': 'متن'}), 19: ('wagtail.blocks.StructBlock', [[('variant', 16), ('title', 17), ('content', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'پرسش'}), 21: ('wagtail.blocks.TextBlock', (), {'label': 'پاسخ'}), 22: ('wagtail.blocks.StructBlock', [[('question', 20), ('answer', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'label': 'پرسشها', 'min_num': 1}), 24: ('wagtail.blocks.StructBlock', [[('items', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'label': 'پیشعنوان', 'required': False}), 26: ('wagtail.blocks.CharBlock', (), {'label': 'عنوان'}), 27: ('wagtail.blocks.TextBlock', (), {'label': 'توضیح', 'required': False}), 28: ('wagtail.blocks.PageChooserBlock', (), {'label': 'صفحه داخلی', 'required': False}), 29: ('wagtail.blocks.URLBlock', (), {'label': 'نشانی بیرونی', 'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'متن پیوند'}), 31: ('wagtail.blocks.StructBlock', [[('page', 28), ('url', 29), ('label', 30)]], {'label': 'پیوند'}), 32: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'اصلی'), ('soft', 'ملایم'), ('product', 'محصول'), ('contact', 'تماس')], 'label': 'نوع'}), 33: ('wagtail.blocks.StructBlock', [[('eyebrow', 25), ('title', 26), ('description', 27), ('link', 31), ('variant', 32)]], {})}, verbose_name='متن مقاله')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('featured_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب ویژه')),
                ('estimated_reading_time', models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='زمان مطالعه (دقیقه)')),
                ('legacy_id', models.PositiveIntegerField(blank=True, editable=False, help_text='ردیابی مقاله\u200cهای منتقل\u200cشده از جدول قدیمی.', null=True, unique=True, verbose_name='شناسه مقاله قدیمی')),
                ('canonical_url_override', models.URLField(blank=True, help_text='فقط اگر این مقاله جای دیگری منتشر شده است.', max_length=500, verbose_name='نشانی کانونیکال جایگزین')),
                ('allow_indexing', models.BooleanField(default=True, verbose_name='اجازه ایندکس شدن')),
                ('allow_following', models.BooleanField(default=True, verbose_name='اجازه دنبال کردن پیوندها')),
                ('og_title', models.CharField(blank=True, max_length=120, verbose_name='عنوان اشتراک\u200cگذاری')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='توضیحات اشتراک\u200cگذاری')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.articleauthor', verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.articlecategory', verbose_name='دسته\u200cبندی')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='تصویر شاخص')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='تصویر اشتراک\u200cگذاری')),
            ],
            options={
                'verbose_name': 'مقاله',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=300, verbose_name='معرفی')),
                ('hero_title', models.CharField(blank=True, max_length=120, verbose_name='عنوان سرصفحه')),
                ('hero_description', models.TextField(blank=True, max_length=300, verbose_name='توضیح سرصفحه')),
                ('featured_categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='articles.articlecategory', verbose_name='دسته\u200cبندی\u200cهای منتخب')),
                ('featured_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.articlepage', verbose_name='مقاله ویژه')),
            ],
            options={
                'verbose_name': 'فهرست مقالات',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='articles.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='articles.ArticlePageTag', to='taggit.Tag', verbose_name='برچسب\u200cها'),
        ),
    ]
