# Generated by Django 6.0.6 on 2026-09-06 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_shorten_order_public_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rial', models.BigIntegerField(verbose_name='amount (Rial)')),
                ('track_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Zibal trackId')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('REDIRECTED', 'Redirected to gateway'), ('PAID_UNVERIFIED', 'Paid, not yet verified'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled by customer')], db_index=True, default='INITIATED', max_length=20)),
                ('zibal_result', models.IntegerField(blank=True, null=True)),
                ('zibal_status', models.IntegerField(blank=True, null=True)),
                ('ref_number', models.CharField(blank=True, default='', max_length=64)),
                ('card_number', models.CharField(blank=True, default='', max_length=32)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
