# Generated by Django 6.0.6 on 2026-07-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='phone number')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('purpose', models.CharField(choices=[('REGISTER', 'register'), ('LOGIN', 'login')], default='REGISTER', max_length=16, verbose_name='purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
            ],
            options={
                'verbose_name': 'phone OTP',
                'verbose_name_plural': 'phone OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
